name: 'Await for Vercel deployment'
description: 'Awaits for a Vercel deployment to be ready'
branding:
  icon: activity
  color: black
inputs:
  deployment-url:
    description: 'Url you want to wait for'
    required: true
  timeout:
    description: 'Duration (in seconds) to wait for a terminal deployment status'
    required: false
    default: '10'
  poll-interval:
    description: 'Duration (in seconds) to wait in between polled Vercel API requests'
    required: false
    default: '1'
outputs:
  deploymentDetails:
    description: 'Forwarded Vercel API response - See https://vercel.com/docs/api#endpoints/deployments/get-a-single-deployment/response-parameters'
runs:
  using: 'node20'
  main: 'github-action-runtime/index.js'
