# Summary:
# Automatically increase the version using semantic versioning
#
# See https://github.com/PaulHatch/semantic-version https://github.com/PaulHatch/semantic-version/tree/v3.1.2
# See https://github.com/phish108/autotag-action https://github.com/phish108/autotag-action/tree/1.1.30

name: 'Auto version increment'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - '*' # XXX for testing

jobs:
  run-semantic-versioning:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See https://github.com/PaulHatch/semantic-version#important-note-regarding-the-checkout-action
      - uses: phish108/autotag-action@1.1.30
        id: next_semantic_version # Outputs: https://github.com/phish108/autotag-action/tree/1.1.30#outputs
        with: # See https://github.com/phish108/autotag-action/tree/1.1.30#inputs
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: "true"
          release-branch: "main"
      - run: |
          echo ${{join(steps.next_semantic_version.outputs.*, ' - ')}}
          echo "Version: ${{steps.next_semantic_version.outputs.tag}}"
          echo "Next version tag: ${{steps.next_semantic_version.outputs.new-tag}}"
