# Summary:
# Automatically increase the version using semantic versioning
#
# See https://github.com/PaulHatch/semantic-version https://github.com/PaulHatch/semantic-version/tree/v3.1.2

name: 'Auto version increment'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - '*' # XXX for testing

jobs:
  run-semantic-versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paulhatch/semantic-version@v3.1.2
        with:
          fetch-depth: 0
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}-prerelease.${increment}"
