# Summary:
# Automatically increase the version using semantic versioning
#
# See https://github.com/PaulHatch/semantic-version https://github.com/PaulHatch/semantic-version/tree/v3.1.2

name: 'Auto version increment'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - '*' # XXX for testing

jobs:
  run-semantic-versioning:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: paulhatch/semantic-version@v3.1.2
        with: # See https://github.com/PaulHatch/semantic-version#usage
          fetch-depth: major_pattern # See https://github.com/PaulHatch/semantic-version#important-note-regarding-the-checkout-action
          tag_prefix: "v" # The prefix to use to identify tags
          major_pattern: "(MAJOR)" # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          minor_pattern: "(MINOR)" # Same as above except indicating a minor change
          format: "${major}.${minor}.${patch}-prerelease.${increment}" # A string to determine the format of the version output
