# Summary:
# Automatically increase the version using semantic versioning
#
# See https://github.com/PaulHatch/semantic-version https://github.com/PaulHatch/semantic-version/tree/v3.1.2
# See https://github.com/phish108/autotag-action https://github.com/phish108/autotag-action/tree/1.1.30

name: 'Auto version increment'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - '*' # XXX for testing

jobs:
  run-semantic-versioning:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See https://github.com/PaulHatch/semantic-version#important-note-regarding-the-checkout-action
      - uses: "marvinpinto/action-automatic-releases@latest"
        with: # See https://github.com/marketplace/actions/automatic-releases#supported-parameters
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automatic release"
          files: |
            CHANGELOG.md
