# Summary:
# Automatically tag and release when changes land on the "main" branch.
#
# See https://github.com/PaulHatch/semantic-version https://github.com/PaulHatch/semantic-version/tree/v3.2
# See https://github.com/marvinpinto/action-automatic-releases https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.0

name: 'Auto release (release candidate)'
on:
  push:
    branches-ignore:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Force fetch all commits - See https://github.com/PaulHatch/semantic-version#important-note-regarding-the-checkout-action

      # Outputs documentation: https://github.com/PaulHatch/semantic-version/blob/master/src/main.ts#L22-L33
      - name: Resolving next Release Candidate version using semantic-version
        uses: paulhatch/semantic-version@v5.0.2
        id: next_semantic_version
        with: # See https://github.com/PaulHatch/semantic-version#usage
          tag_prefix: "v" # The prefix to use to identify tags
          major_pattern: "(MAJOR)" # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          minor_pattern: "(MINOR)" # Same as above except indicating a minor change
          version_format: "${major}.${minor}.${patch}-rc.${increment}" # A string to determine the format of the version output
          short_tags: false # If set to false, short tags like "v1" will not be considered, only full versions tags such as "v1.0.0" will be used to determine the version. XXX This is necessary because of our "auto-tag-on-release" which updates "latest-rc" and would cause conflicts
          bump_each_commit: true # If this input is set to true, every commit will be treated as a new version, bumping the patch, minor, or major version based on the commit message.

      - name: Printing semantic-version outputs (for debugging)
        run: |
          echo "Most useful outputs:"
          echo "Next version: ${{steps.next_semantic_version.outputs.version}}"
          echo "Next version tag: ${{steps.next_semantic_version.outputs.version_tag}}"
          echo "\n All outputs:"
          echo "version: ${{steps.next_semantic_version.outputs.version}}"
          echo "major: ${{steps.next_semantic_version.outputs.major}}"
          echo "minor: ${{steps.next_semantic_version.outputs.minor}}"
          echo "patch: ${{steps.next_semantic_version.outputs.patch}}"
          echo "increment: ${{steps.next_semantic_version.outputs.increment}}"
          echo "version_type: ${{steps.next_semantic_version.outputs.version_type}}"
          echo "changed: ${{steps.next_semantic_version.outputs.changed}}"
          echo "version_tag: ${{steps.next_semantic_version.outputs.version_tag}}"
          echo "previous_commit: ${{steps.next_semantic_version.outputs.previous_commit}}"
          echo "current_commit: ${{steps.next_semantic_version.outputs.current_commit}}"

      - name: Creating Git release tag for the ${{steps.next_semantic_version.outputs.version}} version
        uses: marvinpinto/action-automatic-releases@10bdce64abdb4558a2ee6983192242be40d631d8 # Pin "latest" https://github.com/marvinpinto/action-automatic-releases/commit/10bdce64abdb4558a2ee6983192242be40d631d8 necessary to avoid "The `set-env` command is disabled."
        with: # See https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.0#supported-parameters
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{steps.next_semantic_version.outputs.version}}
          prerelease: true
          title: "Automatic release ${{steps.next_semantic_version.outputs.version}}"
          files: |
            CHANGELOG.md

      - name: Updating Git release tag for "latest-rc" version
        uses: marvinpinto/action-automatic-releases@10bdce64abdb4558a2ee6983192242be40d631d8 # Pin "latest" https://github.com/marvinpinto/action-automatic-releases/commit/10bdce64abdb4558a2ee6983192242be40d631d8 necessary to avoid "The `set-env` command is disabled."
        with: # See https://github.com/marvinpinto/action-automatic-releases/tree/v1.1.0#supported-parameters
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest-rc
          prerelease: true
          title: "Latest release (auto-update) - UNSAFE for production usage"
          files: |
            CHANGELOG.md
