# Summary:
# Test the GitHub Action using an integration test.
# Makes sure the GitHub Action works properly when running on a clean machine, without building anything (integration test).
# This integration test will break if the Vercel project or deployment are deleted, or if the VERCEl_TOKEN doesn't have access to the deployment url.
#
# See https://github.com/actions/checkout https://github.com/actions/checkout/releases/tag/v2

name: 'GitHub Action integration test'
on:
  pull_request:
  push:

jobs:
  run-integration-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn # Install all dependencies
      - uses: ./
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEl_TOKEN }}
        with:
          # Testing whether some existing vercel deployment is properly deployed
          deployment-url: "nextjs-bzyss249z.vercel.app" # In our case (at Unly), the "VERCEL_DOMAIN" secret value should probably use the same value
          timeout: 10
